version: "3.8"
services:
  3x-ui:
    container_name: 3x-ui
    build: .
    image: 3x-ui:latest
    command: air
    ports:
      - 8080:8080
    volumes:
      - $PWD:/app
      # - /path/to/your/other/volume:/path/in/container
      - $PWD/db:/etc/x-ui/
      - $PWD/cert:/root/cert/
    environment:
      - ENV_VAR_NAME=your_value
    networks:
      - your_network

networks:
  your_network:
    driver: bridge
