version: "3.8"

services:
  3x-ui:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 3x-ui
    volumes:
      - ./:/app
      - /etc/x-ui:/etc/x-ui
    ports:
      - "8980:8080" # Adjust the port according to your application's needs
    environment:
      - TZ=Asia/Tehran
    network_mode: host
    restart: unless-stopped
    command: air
