version: "3"

services:
  3x-ui:
    build: .
    container_name: 3x-ui
    volumes:
      - $PWD:/app # Mount the project directory inside the container
      - $PWD/db:/etc/x-ui/
      - $PWD/cert:/root/cert/
    environment:
      XRAY_VMESS_AEAD_FORCED: "false"
    network_mode: host
    restart: unless-stopped
