version: "3"

services:
  3x-ui:
    build: .
    container_name: 3x-ui
    hostname: yourhostname
    volumes:
      - $PWD:/app # Mount the project directory inside the container
      - $PWD/db:/etc/x-ui/
      - $PWD/cert:/root/cert/
      - /app/node_modules # Avoid mounting node_modules from host
    environment:
      XRAY_VMESS_AEAD_FORCED: "false"
    tty: true
    network_mode: host
    restart: unless-stopped
